services:
  - type: web
    name: transfer-order-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm run start --workspace=server
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
